// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAlumnos;

#nullable disable

namespace WebApiAlumnos.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221002002845_Agencias")]
    partial class Agencias
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiAlumnos.Entidades.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("Año")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("WebApiAlumnos.Entidades.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auto");
                });

            modelBuilder.Entity("WebApiAlumnos.Entidades.Agencia", b =>
                {
                    b.HasOne("WebApiAlumnos.Entidades.Auto", "Auto")
                        .WithMany("Agencias")
                        .HasForeignKey("AutoId");

                    b.Navigation("Auto");
                });

            modelBuilder.Entity("WebApiAlumnos.Entidades.Auto", b =>
                {
                    b.Navigation("Agencias");
                });
#pragma warning restore 612, 618
        }
    }
}
